# Generated by Django 4.2.5 on 2023-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Clothing', 'Clothings'), ('Electronics', 'Electronics'), ('Stationaries', 'Stationaries'), ('Groceries', 'Groceries')], max_length=100)),
                ('product_type', models.CharField(choices=[('Featured', 'Featured'), ('Latest', 'Latest')], max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
    ]
